sudo: false
language: php
services:
  - mysql
notifications:
  slack:
    secure: AhtX1RztruH3HYMnXGH1IcGXWRNTdnjJIRVMHI4zeKQfFaomyJstLK6LD43vKxEaefMrHALhcB7csEvcQYBmlgvNgxOzcjHuGE5BVPW2OM6OUt/lv8r6979o0iIKC1dS7Ngc6S41UqWUy7CzmSxNSiapxT+gg0P7T2mHcYCrIrNb14gLLW8oKlem9JxG2Os1U47PGe9n5vNymCdLERprnzuDYkyYkzwLjNFwsl8rkFTU1mSScI6K+O/sbKNe1UEBXzJYAcB0Ta0j7ORPwJua0j+qAcqm9d9QUpzsrQyXev69yGCa0eSDDSiRWUIidpn3wq1uEHYjkFPF1XaXeUJYU9tvan1H7wjynCFmzJAQnxnEGOR8LwE+r6aYgWQfbwSIrxw+Hnc6CK90tA79mgsZoRxeHnLZo+hukeaXIUWn3kNCiRR/vWtwd67bzG3LOq4evDs34a1CzfdJWF17nAoilDI7kKUyXo/I4lbwPB1aveoCracTDKuCSl+IjQkSTH2a2afYk6pibFImAN73G50IFqk5DVgVwGMlCI6WvXs8FN1Mi9vR49F+Sxe5gCPx/Vdx9sGIfQEGC628sO92TKASEdcAjMtxaCKMZUnlBG9M0IyIb7RP2Uh3twTOaWaowZ81Zcs8hY2pFPQTLUpBS+XOqP7WmbPsDD+V+c0r613qSeE=
    on_success: change
    on_failure: change
  email:
    on_success: never
    on_failure: never
branches:
  only:
  - master
  - develop
cache:
  directories:
  - vendor
  - "$HOME/.composer/cache"
matrix:
  include:
  - php: 7.4
    env: WP_VERSION=latest
  - php: 7.3
    env: WP_VERSION=latest
  - php: 7.2
    env: WP_VERSION=latest
  - php: 5.6
    env: WP_VERSION=latest
  - name: Legacy
    php: 5.6
    env: WP_VERSION=4.9.11
  - name: Coding Standards
    php: 7.3
    env: WP_TRAVISCI=phpcs
before_install:
  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || true
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ -f composer.lock ]] ; then
      rm composer.lock
    fi
install:
  - composer install --prefer-dist --no-interaction
before_script:
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  fi
script:
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
    composer phpcs
  else
    composer run-tests
  fi
